var commons = {
    raceType:               ["Humanoid", "Animal", "Undead", "Outsider"],
    size:                   ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan", "Colossal"],
    speeds:                 ["Walk", "Fly", "Swim", "Climb", "Dig"],
    bonusType:              ["None", "Enhancement", "Holy", "Natural", "Racial", "Morale"],
    attackType:             ["Poison", "Fire", "Ice", "Acid", "Sound", "Electricity", "Holy", "Unholy"],
    abilities:              ["Str", "Dex", "Con", "Int", "Wis", "Cha"],
    attackBonusType:        ["Slow", "Medium", "Fast"],
    savingThrowsBonusType:  ["Slow", "Fast"],
    classType:              ["NPC", "PC", "Prestige"],
    featType:               ["General", "Fighter", "Ranger"],
    skills:                 [
        { name: "Appraise",                     modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Balance",                      modifier: "Dex",   trainedOnly: false,  synergies: ["Tumble"] },
        { name: "Bluff",                        modifier: "Cha",   trainedOnly: false,  synergies: [] },
        { name: "Climb",                        modifier: "Str",   trainedOnly: false,  synergies: [] },
        { name: "Concentration",                modifier: "Con",   trainedOnly: false,  synergies: [] },
        { name: "Craft (Alchemy)",              modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Craft (Armorsmithing)",        modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Craft (Bowmaking)",            modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Craft (Weaponsmithing)",       modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Craft (Trapmaking)",           modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Decipher Script",              modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Diplomacy",                    modifier: "Cha",   trainedOnly: false,  synergies: ["Knowledge (nobility and royalty)", "Bluff", "Sense Motive"] },
        { name: "Disable Device",               modifier: "Dex",   trainedOnly: true,   synergies: [] },
        { name: "Disguise",                     modifier: "Cha",   trainedOnly: false,  synergies: ["Bluff"] },
        { name: "Escape Artist",                modifier: "Dex",   trainedOnly: false,  synergies: [] },
        { name: "Forgery",                      modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Gather Information",           modifier: "Cha",   trainedOnly: false,  synergies: ["Knowledge (local)"] },
        { name: "Handle Animal",                modifier: "Cha",   trainedOnly: true,   synergies: [] },
        { name: "Heal",                         modifier: "Wis",   trainedOnly: false,  synergies: [] },
        { name: "Hide",                         modifier: "Dex",   trainedOnly: false,  synergies: [] },
        { name: "Intimidate",                   modifier: "Cha",   trainedOnly: false,  synergies: ["Bluff"] },
        { name: "Jump",                         modifier: "Str",   trainedOnly: false,  synergies: ["Tumble"] },
        { name: "Knowledge (Arcana)",                       modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Architecture and engineering)", modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Dungeoneering)",                modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Geography)",                    modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (History)",                      modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (local)",                        modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Nature)",                       modifier: "Int",   trainedOnly: true,   synergies: ["Survival"] },
        { name: "Knowledge (nobility and royalty)",         modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Religion)",                     modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (The planes)",                   modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Bowmaking)",                    modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Weaponsmithing)",               modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Knowledge (Trapmaking)",                   modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Listen",                       modifier: "Wis",   trainedOnly: false,  synergies: [] },
        { name: "Move Silently",                modifier: "Dex",   trainedOnly: false,  synergies: [] },
        { name: "Open Lock",                    modifier: "Dex",   trainedOnly: true,   synergies: [] },
        { name: "Perform",                      modifier: "Cha",   trainedOnly: false,  synergies: [] },
        { name: "Profession (Any)",             modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Ride",                         modifier: "Dex",   trainedOnly: false,  synergies: ["Handle Animal"] },
        { name: "Search",                       modifier: "Int",   trainedOnly: false,  synergies: [] },
        { name: "Sense Motive",                 modifier: "Wis",   trainedOnly: false,  synergies: [] },
        { name: "Sleight Of Hand",              modifier: "Dex",   trainedOnly: true,   synergies: ["Bluff"] },
        { name: "Speak Language",               modifier: "Int",   trainedOnly: true,   synergies: [] },
        { name: "Spellcraft",                   modifier: "Int",   trainedOnly: true,   synergies: ["Knowledge (Arcana)"] },
        { name: "Spot",                         modifier: "Wis",   trainedOnly: false,  synergies: [] },
        { name: "Survival",                     modifier: "Wis",   trainedOnly: false,  synergies: ["Knowledge (Nature)"] },
        { name: "Swim",                         modifier: "Str",   trainedOnly: false,  synergies: [] },
        { name: "Tumble",                       modifier: "Dex",   trainedOnly: true,   synergies: ["Jump"] },
        { name: "Use Magic Device",             modifier: "Cha",   trainedOnly: true,   synergies: ["Decipher Script", "Spellcraft"] },
        { name: "Use Rope",                     modifier: "Dex",   trainedOnly: false,  synergies: [] }
    ]
}

module.exports = commons;