export const PATHS = {
  HOME: '', 
  DICE_ROLLER : 'dice-roller',        
  CHARACTER_SHEET: 'character-sheet',    
  INIT_MANAGER: 'initMgr',    
  CAMPAIGNS: 'campaigns',           
  CAMPAIGN: 'campaign',           
  ADD_CAMPAIGN: 'add-campaign',           
  PARTY_EDITOR: 'party-editor', 
  CLASSES: 'classes', 
  CHARACTER_CLASS: 'character-class',
  CHARACTERS_LIST: 'characters-list',
  LOGIN: 'login',
  REGISTER: 'register',
  RACES: 'races',
  RACE_FORM: 'race-form',
  ADD_SPECIAL_ABILITIES: 'app-special-abilities',
  APP_SPECIAL_ABILITIES_FORM: 'app-special-abilities-form', 
  DND_MANAGER: 'app-special-abilities-form',
  SETTING: 'setting',  
}
